# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dream big
subtitle: Never name your product Pied Piper.
author: Vicky Luo
language: en
timezone:


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vickyluoluo.github.io/      # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:abbrlink.html
permalink_defaults:
abbrlink:
  alg: crs32
  rep: hex

# CDN Setting
## Docs: https://www.jsdelivr.com/?docs=gh
## If Github Pages deploy，you can ues jsdelivr settings
#
#jsdelivr:
#  jsdelivr_url: https://cdn.jsdelivr.net/gh/
#  github_username: V-Vincen


# Custom Setting Start

# Site settings
SEOTitle: dream big
email: vicky123.luo@outlook.com
description: "It's a personal blog..."
keyword: "Blog"
header-img: img/header_img/home-bg.jpg
archives-img: img/header_img/archive_bg.jpg


# Favicon settings
favicon: img/avatar/avatar.png


# Signature Setup
signature: true # show signature
signature-img: img/signature/vicky-white.png


# Wave settings
wave: true


# SNS Settings
# RSS: true
# github_username: VickyLuoLuo
# twitter_username:
# instagram_username:
# facebook_username:
# linkedin_username:
# zhihu_username:
# weibo_username: WVincen
theme_by: false


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "Success comes from the pursuit of perfection."
sidebar-avatar: img/avatar/about-me.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- visitor   # busuanzi: https://busuanzi.ibruce.info/
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "Sage Renn",
        href: "https://sagerenn.github.io/"
    }
]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md
##
gitalk:
  owner: VickyLuoLuo                          # 'GitHub repo owner'
  admin: VickyLuoLuo                         # 'GitHub repo'
  repo: VickyLuoLuo.github.io                          # ['GitHub repo owner and collaborators, only these guys can initialize github issues']
  clientID: 174c71e299e44fbdb98f                      # 'GitHub Application Client ID'
  clientSecret: b89fcac752fa9157640097d65ec0796ba699eaa4                  # 'GitHub Application Client Secret'
  perPage: 10                     # Pagination size, with maximum 100.
  pagerDirection: last            # Comment sorting direction, available values are last and first.
  createIssueManually: true      # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true
  language: en                    # Localization language key, en, zh-CN and zh-TW are currently available.
  maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded.Default 250.

## Gitment Settings
## Doc:https://github.com/imsun/gitment
##

#gitment:
#  owner: VickyLuoLuo                                        # Your GitHub ID. Required.
#  repo: VickyLuoLuo.github.io                               # The repository to store your comments. Make sure you're repo's owner. Required.
#  client_id: 174c71e299e44fbdb98f                           # GitHub client ID. Required.
#  client_secret: b89fcac752fa9157640097d65ec0796ba699eaa4   # GitHub client secret. Required.
#  desc: blog comment back up                                # An optional description for your page, used in issue's body. Default ''.
#  perPage: 10                                               # An optional number to which comments will be paginated. Default 20.
#  maxCommentHeight: 250                                     # An optional number to limit comments' max height, over which comments will be folded. Default 250.

## Disqus settings
##
# disqus_username: your-disqus-ID


# Analytics settings

## Google Analytics
ga_track_id: UA-xxxxxx-xx   # Format: UA-xxxxxx-xx

## Baidu Analytics
ba_track_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## Sitemap
sitemap:
  path: sitemap.xml

## Baidusitemap
baidusitemap:
    path: baidusitemap.xml

baidu_push: true

# Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
external_link: true   # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
##
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'


# Build Settings
anchorjs: true    # if you want to customize anchor. check out line:26 of `anchorjs.ejs`


# article top
top: true


# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: true


# top scroll progress
scroll: true


# Tip
tip:
  enable: true
  copyright: If the images or anything used in the blog infringe your copyright, please contact me to delete them. Thank you!


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: false


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor: true


# Search Setting
## Search: https://go.kieran.top/post/45/
## Dependencies: https://github.com/V-Vincen/hexo-generator-zip-search
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1


# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife


# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
gitter:
  room: your-community/your-room


# Deployment
## Docs: https://hexo.io/docs/deployment.html
##
deploy:
  type: git
  repo: https://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@github.com/VickyLuoLuo/VickyLuoLuo.github.io.git
  branch: main